### ISSUE TITLE
Improve render_scene() to more user-frinedly and flexible

### ISSUE THREAD

**Issue by sumiya-kuroda** [htem/FANC_auto_recon#18]
[`render_scene()` in `proofreading/proofreading_utils.py`](https://github.com/htem/FANC_auto_recon/blob/main/proofreading/proofreading_utils.py#L99) is a very useful function to render neurons in a neuroglancer state. But the function is not updated since when we were using locally-saved tables for annotations before CAVE, and it is time to improve this function.

- [ ] Make it able to use user-specified layers. (Add **kwargs argument to this function, and you can now add `SegmentationLayerConfig` of nuclei prediction, for example)
- [x] Accept more annotation types. (e.g. `spheres`)
- [x] Use `client.info.viewer_site()` to get URL.
- [x] Change value names to CAVE format: i.e., from `xyz` to `pt_position` and `segment_id` to `pt_root_id`.
- [ ] Make it able to change colors not only for selected segmentation but also annotations (if possible)

**Comment by jasper-tms** [comment]
Forrest just set the viewer site for us, so this now works:

```
> client.info.viewer_site()
'https://neuromancer-seung-import.appspot.com/'
```

Once we merge #19 I'm happy to work with you on improving this function. I also thought that `render_scene(from_table=cave_table_name)` would be a nice kwarg to implement, so that users can easily make a scene showing all the neurons labeled in some CAVE table.

**Comment by jasper-tms** [comment]
EDIT: Sorry, I was confusing myself, the feature I describe in the comment below is related to plot_neurons, not render_scene, so isn't relevant to this issue.

Also `warp_to_template=True/False` to plot the neurons and volume meshes aligned to the template instead of in native FANC-space. This would be useful for making paper figures. If this is true we don't need to warp the volume meshes, we can just use the .stl files that are already in template space. But we'd need to warp the neurons.

**Comment by jasper-tms** [comment]
also `render_scene(from_points=blah)` where users can supply points and we will look up those points' rootIDs for the user.

**Comment by jasper-tms** [comment]
Actually the first argument, named `neurons`, should just be flexible enough to be able to take a list or a DataFrame with segIDs, a np.array with point locations, or a str specifying a CAVE table name. I'll implement this.

**Comment by jasper-tms** [comment]
I rewrote most of `render_scene`. The functionality is mostly unchanged, except that I removed some kwargs I thought were necessary and added a few new ones for selecting which optional layers to include in the scene. The rewrite should I think make it a bit easier to continue adding features, and hopefully improves readability.

I added a docstring which optimistically describes the flexibility that I want for the `neurons` argument, but I haven't yet implemented most of that flexibility. That'll come next.

**Comment by sumiya-kuroda** [comment]
Sorry, I accidentally linked the pull request. Now it is detached.

**Comment by sumiya-kuroda** [comment]
The update looks very good.
One question: do you think there will be any situations that users want to add some `ImageLayer `or `SegmentationLayer`, other than the nucleus segmentation layer? For example, [I used to use three image and two segmentation layers ](https://github.com/htem/FANC_auto_recon/blob/main/nuclei_prediction/proofread_nuclei.ipynb) like below. Some of them are related to the nuclei segmentation, and I think [your current implementation](https://github.com/htem/FANC_auto_recon/blob/reorganize/fanc/statebuilder.py#L204) is sufficient for that.
```
imgTokyo = ImageLayerConfig(name = 'FANCv4-jp',
                                    source = auth.get_cv_path('Image_Tokyo')['url'])
img = ImageLayerConfig(name = 'FANCv4',
                                    source = auth.get_cv_path('Image')['url'])
seg = SegmentationLayerConfig(name = 'seg_Mar2021_proofreading',
                                    source = auth.get_cv_path('FANC_production_segmentation')['url'])     
nuc_Aug = ImageLayerConfig(name = 'nuc',
                                    source = auth.get_cv_path('nuclei_map_Aug2021')['url'])      
nuc_seg_Aug = ImageLayerConfig(name = 'nuc_seg',
                                    source = auth.get_cv_path('nuclei_seg_Aug2021')['url'])        
ann = AnnotationLayerConfig(name='nuc_soma_Aug2021',
                            mapping_rules=lines,
                            tags=['neuron', 'glia','false_positive','soma_need_check'],
                            active = True)
sb = StateBuilder(layers=[imgTokyo, seg, img, nuc_Aug, nuc_seg_Aug, ann],
                  resolution=[4.3,4.3,45],
                  view_kws=view_options)
```

**Comment by jasper-tms** [comment]
Yes, it seems like a good idea to allow users to provide additional layers.

**Comment by jasper-tms** [comment]
Another nice argument to implement would be a `nuclei=<Iterable of segIDs or point coordinates>` to allow users to specify nuclei IDs to be selected in the nucleus segmentation

**Comment by sumiya-kuroda** [comment]
`render_scene` can now also [handle nucleus ids](https://github.com/htem/FANC_auto_recon/blob/ae5c5366bfd635e63fff6339d2c5343a09b01f36/fanc/statebuilder.py#L252).

**Comment by jasper-tms** [comment]
We've made a lot of updates to `render_scene` recently, so that most of its features are documented and fairly user-friendly. There are still a number of things that could be improved but I'm going to close this for now as I don't see the two remaining todo items here as terribly high priorities, but we can certainly re-open this if you decide to work on them at some point. Thanks again for working with me on this function!
